# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(526, 557)
        Dialog.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 8px 20px;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"     font-size: 12px;\n"
"}\n"
"\n"
" QTableWidget {\n"
"    border: 1px solid #dcdde1;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"")
        self.bookings = QtWidgets.QGroupBox(Dialog)
        self.bookings.setGeometry(QtCore.QRect(20, 310, 491, 211))
        self.bookings.setObjectName("bookings")
        self.bookings_table = QtWidgets.QTableWidget(self.bookings)
        self.bookings_table.setGeometry(QtCore.QRect(-20, 21, 511, 171))
        self.bookings_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bookings_table.setObjectName("bookings_table")
        self.bookings_table.setColumnCount(0)
        self.bookings_table.setRowCount(0)
        self.machines = QtWidgets.QGroupBox(Dialog)
        self.machines.setGeometry(QtCore.QRect(20, 50, 491, 191))
        self.machines.setObjectName("machines")
        self.machine_table = QtWidgets.QTableWidget(self.machines)
        self.machine_table.setGeometry(QtCore.QRect(0, 21, 256, 171))
        self.machine_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.machine_table.setObjectName("machine_table")
        self.machine_table.setColumnCount(0)
        self.machine_table.setRowCount(0)
        self.add_btn = QtWidgets.QPushButton(self.machines)
        self.add_btn.setGeometry(QtCore.QRect(270, 140, 91, 31))
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setObjectName("add_btn")
        self.del_btn = QtWidgets.QPushButton(self.machines)
        self.del_btn.setGeometry(QtCore.QRect(380, 140, 91, 31))
        self.del_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_btn.setObjectName("del_btn")
        self.machine_line = QtWidgets.QLineEdit(self.machines)
        self.machine_line.setGeometry(QtCore.QRect(280, 70, 191, 31))
        self.machine_line.setObjectName("machine_line")
        self.label = QtWidgets.QLabel(self.machines)
        self.label.setGeometry(QtCore.QRect(280, 30, 171, 31))
        self.label.setStyleSheet("    color: #2c3e50;\n"
"    font-weight: normal;\n"
"     font-size: 14px;\n"
"    qproperty-alignment: AlignCenter;")
        self.label.setObjectName("label")
        self.search_line = QtWidgets.QLineEdit(Dialog)
        self.search_line.setGeometry(QtCore.QRect(40, 259, 361, 41))
        self.search_line.setPlaceholderText("")
        self.search_line.setObjectName("search_line")
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(410, 260, 91, 31))
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn.setObjectName("search_btn")
        self.machine_icon = QtWidgets.QLabel(Dialog)
        self.machine_icon.setGeometry(QtCore.QRect(460, 0, 51, 51))
        self.machine_icon.setText("")
        self.machine_icon.setPixmap(QtGui.QPixmap(":/machine/icons8-washing-machine-94.png"))
        self.machine_icon.setScaledContents(True)
        self.machine_icon.setObjectName("machine_icon")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.bookings.setTitle(_translate("Dialog", "Bookings"))
        self.machines.setTitle(_translate("Dialog", "Machines"))
        self.add_btn.setText(_translate("Dialog", "Add"))
        self.del_btn.setText(_translate("Dialog", "Delete"))
        self.label.setText(_translate("Dialog", "Machine name:"))
        self.search_btn.setText(_translate("Dialog", "Search"))
import machine_rc
