# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authentication.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 582)
        self.welcome_label = QtWidgets.QLabel(Dialog)
        self.welcome_label.setGeometry(QtCore.QRect(170, 10, 241, 81))
        self.welcome_label.setAutoFillBackground(False)
        self.welcome_label.setStyleSheet("    font-family: \'Segoe UI\';\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2C3E50;\n"
"    padding: 10px 0;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.welcome_label.setObjectName("welcome_label")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(60, 90, 511, 461))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.groupBox = QtWidgets.QGroupBox(self.login_page)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 451, 381))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.email = QtWidgets.QLineEdit(self.groupBox)
        self.email.setGeometry(QtCore.QRect(60, 80, 321, 51))
        self.email.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(60, 160, 321, 51))
        self.password.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.password.setMaxLength(8)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.login_btn = QtWidgets.QPushButton(self.groupBox)
        self.login_btn.setGeometry(QtCore.QRect(60, 240, 321, 41))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop:0 #4A90E2, stop:1 #357ABD);\n"
"color: white;\n"
"border-radius: 6px;\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.signup_btn2 = QtWidgets.QPushButton(self.groupBox)
        self.signup_btn2.setGeometry(QtCore.QRect(260, 300, 61, 41))
        self.signup_btn2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup_btn2.setStyleSheet("color: #4A90E2;\n"
"border-radius: 6px;\n"
"\n"
"")
        self.signup_btn2.setObjectName("signup_btn2")
        self.no_acc_label = QtWidgets.QLabel(self.groupBox)
        self.no_acc_label.setGeometry(QtCore.QRect(110, 300, 161, 41))
        self.no_acc_label.setStyleSheet("    font-family: \'Segoe UI\';\n"
"    font-size: 12px;\n"
"    color: #2C3E50;\n"
"    padding: 10px 0;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.no_acc_label.setObjectName("no_acc_label")
        self.login_label = QtWidgets.QLabel(self.groupBox)
        self.login_label.setGeometry(QtCore.QRect(90, 10, 191, 51))
        self.login_label.setStyleSheet("    font-family: \'Segoe UI\';\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2C3E50;\n"
"    padding: 10px 0;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.login_label.setObjectName("login_label")
        self.update_btn_2 = QtWidgets.QPushButton(self.groupBox)
        self.update_btn_2.setGeometry(QtCore.QRect(150, 330, 121, 41))
        self.update_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_btn_2.setStyleSheet("color: #4A90E2;\n"
"border-radius: 6px;\n"
"\n"
"")
        self.update_btn_2.setObjectName("update_btn_2")
        self.stackedWidget.addWidget(self.login_page)
        self.signup_page = QtWidgets.QWidget()
        self.signup_page.setObjectName("signup_page")
        self.groupBox_2 = QtWidgets.QGroupBox(self.signup_page)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 461, 421))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.SignUpLabel = QtWidgets.QLabel(self.groupBox_2)
        self.SignUpLabel.setGeometry(QtCore.QRect(110, 0, 171, 51))
        self.SignUpLabel.setStyleSheet("    font-family: \'Segoe UI\';\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2C3E50;\n"
"    padding: 10px 0;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.SignUpLabel.setObjectName("SignUpLabel")
        self.email_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.email_2.setGeometry(QtCore.QRect(60, 50, 321, 51))
        self.email_2.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.email_2.setInputMask("")
        self.email_2.setObjectName("email_2")
        self.phone_no = QtWidgets.QLineEdit(self.groupBox_2)
        self.phone_no.setGeometry(QtCore.QRect(60, 120, 321, 51))
        self.phone_no.setAccessibleDescription("")
        self.phone_no.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.phone_no.setObjectName("phone_no")
        self.password_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.password_2.setGeometry(QtCore.QRect(60, 190, 321, 51))
        self.password_2.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.password_2.setMaxLength(8)
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.signup_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.signup_btn.setGeometry(QtCore.QRect(60, 340, 321, 41))
        self.signup_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup_btn.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop:0 #4A90E2, stop:1 #357ABD);\n"
"color: white;\n"
"border-radius: 6px;\n"
"")
        self.signup_btn.setObjectName("signup_btn")
        self.confirm_password = QtWidgets.QLineEdit(self.groupBox_2)
        self.confirm_password.setGeometry(QtCore.QRect(60, 260, 321, 51))
        self.confirm_password.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.confirm_password.setMaxLength(8)
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password.setObjectName("confirm_password")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(280, 20, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget.addWidget(self.signup_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 20, 451, 411))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.SignUpLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.SignUpLabel_3.setGeometry(QtCore.QRect(80, 0, 261, 51))
        self.SignUpLabel_3.setStyleSheet("    font-family: \'Segoe UI\';\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    color: #2C3E50;\n"
"    padding: 10px 0;\n"
"    qproperty-alignment: AlignCenter;\n"
"\n"
"")
        self.SignUpLabel_3.setObjectName("SignUpLabel_3")
        self.old_telephone = QtWidgets.QLineEdit(self.groupBox_3)
        self.old_telephone.setGeometry(QtCore.QRect(60, 50, 321, 51))
        self.old_telephone.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.old_telephone.setObjectName("old_telephone")
        self.new_telephone = QtWidgets.QLineEdit(self.groupBox_3)
        self.new_telephone.setGeometry(QtCore.QRect(60, 120, 321, 51))
        self.new_telephone.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.new_telephone.setObjectName("new_telephone")
        self.old_password = QtWidgets.QLineEdit(self.groupBox_3)
        self.old_password.setGeometry(QtCore.QRect(60, 190, 321, 51))
        self.old_password.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.old_password.setMaxLength(8)
        self.old_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.old_password.setObjectName("old_password")
        self.update_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.update_btn.setGeometry(QtCore.QRect(60, 340, 321, 41))
        self.update_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_btn.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                            stop:0 #4A90E2, stop:1 #357ABD);\n"
"color: white;\n"
"border-radius: 6px;\n"
"")
        self.update_btn.setObjectName("update_btn")
        self.new_password = QtWidgets.QLineEdit(self.groupBox_3)
        self.new_password.setGeometry(QtCore.QRect(60, 260, 321, 51))
        self.new_password.setStyleSheet("background-color: #FAFAFA;\n"
"border: 1px solid #CED6E0;\n"
"border-radius: 5px;\n"
"padding: 6px;\n"
"")
        self.new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password.setObjectName("new_password")
        self.stackedWidget.addWidget(self.page)
        self.machine_icon = QtWidgets.QLabel(Dialog)
        self.machine_icon.setGeometry(QtCore.QRect(540, 10, 51, 51))
        self.machine_icon.setText("")
        self.machine_icon.setPixmap(QtGui.QPixmap(":/machine/icons8-washing-machine-94.png"))
        self.machine_icon.setScaledContents(True)
        self.machine_icon.setObjectName("machine_icon")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_label.setText(_translate("Dialog", "Welcome to Yiqa"))
        self.email.setPlaceholderText(_translate("Dialog", "Enter your email or username"))
        self.password.setPlaceholderText(_translate("Dialog", "Enter your password"))
        self.login_btn.setText(_translate("Dialog", "Login"))
        self.signup_btn2.setText(_translate("Dialog", "Sign up"))
        self.no_acc_label.setText(_translate("Dialog", "Don\'t have an account?"))
        self.login_label.setText(_translate("Dialog", "Log in"))
        self.update_btn_2.setText(_translate("Dialog", "Update your details"))
        self.SignUpLabel.setText(_translate("Dialog", "Sign up"))
        self.email_2.setPlaceholderText(_translate("Dialog", "Enter your email or username"))
        self.phone_no.setInputMask(_translate("Dialog", "+90 000-000-0000;_"))
        self.phone_no.setPlaceholderText(_translate("Dialog", "Enter your telephone no"))
        self.password_2.setPlaceholderText(_translate("Dialog", "Create your password"))
        self.signup_btn.setText(_translate("Dialog", "Sign up"))
        self.confirm_password.setPlaceholderText(_translate("Dialog", "Confirm your password"))
        self.comboBox.setItemText(0, _translate("Dialog", "Student"))
        self.comboBox.setItemText(1, _translate("Dialog", "Admin"))
        self.SignUpLabel_3.setText(_translate("Dialog", "Update your credentials"))
        self.old_telephone.setInputMask(_translate("Dialog", "+90 000-000-0000;_"))
        self.old_telephone.setPlaceholderText(_translate("Dialog", "Enter old telephone no"))
        self.new_telephone.setInputMask(_translate("Dialog", "+90 000-000-0000;_"))
        self.new_telephone.setPlaceholderText(_translate("Dialog", "Enter new telephone no"))
        self.old_password.setPlaceholderText(_translate("Dialog", "Enter old password"))
        self.update_btn.setText(_translate("Dialog", "Update"))
        self.new_password.setPlaceholderText(_translate("Dialog", "Enter new password"))
import machine_rc
