# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(533, 573)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 80, 451, 431))
        self.stackedWidget.setStyleSheet("QWidget {\n"
"    background-color: #f5f7fa;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: bold;\n"
"    margin-bottom: 5px;\n"
"     font-size: 18px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 8px 20px;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"     font-size: 14px;\n"
"}\n"
"\n"
" QTableWidget {\n"
"    border: 1px solid #dcdde1;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.date = QtWidgets.QWidget()
        self.date.setObjectName("date")
        self.date_label = QtWidgets.QLabel(self.date)
        self.date_label.setGeometry(QtCore.QRect(40, 30, 351, 41))
        self.date_label.setObjectName("date_label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.date)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 90, 361, 241))
        self.calendarWidget.setStyleSheet("    selection-background-color: #5dade2;\n"
"    selection-color: white;\n"
"    font-size: 13px;\n"
"    background-color: white;\n"
"    alternate-background-color: #f2f3f4;\n"
"\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.next_btn = QtWidgets.QPushButton(self.date)
        self.next_btn.setEnabled(True)
        self.next_btn.setGeometry(QtCore.QRect(300, 360, 101, 41))
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setObjectName("next_btn")
        self.stackedWidget.addWidget(self.date)
        self.time = QtWidgets.QWidget()
        self.time.setObjectName("time")
        self.times_table = QtWidgets.QTableWidget(self.time)
        self.times_table.setGeometry(QtCore.QRect(50, 70, 341, 271))
        self.times_table.setStyleSheet("QTableWidget {\n"
"    gridline-color: #dcdde1;\n"
"    selection-background-color: #aed6f1;\n"
"    selection-color: #1a5276;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"")
        self.times_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.times_table.setObjectName("times_table")
        self.times_table.setColumnCount(0)
        self.times_table.setRowCount(0)
        self.timeslot_label = QtWidgets.QLabel(self.time)
        self.timeslot_label.setGeometry(QtCore.QRect(50, 20, 341, 41))
        self.timeslot_label.setObjectName("timeslot_label")
        self.back_btn = QtWidgets.QPushButton(self.time)
        self.back_btn.setGeometry(QtCore.QRect(50, 370, 101, 41))
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setObjectName("back_btn")
        self.next_btn_2 = QtWidgets.QPushButton(self.time)
        self.next_btn_2.setGeometry(QtCore.QRect(320, 370, 101, 41))
        self.next_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn_2.setObjectName("next_btn_2")
        self.stackedWidget.addWidget(self.time)
        self.machine = QtWidgets.QWidget()
        self.machine.setObjectName("machine")
        self.machines_table = QtWidgets.QTableWidget(self.machine)
        self.machines_table.setGeometry(QtCore.QRect(40, 80, 351, 271))
        self.machines_table.setStyleSheet("QTableWidget {\n"
"    gridline-color: #dcdde1;\n"
"    selection-background-color: #aed6f1;\n"
"    selection-color: #1a5276;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"")
        self.machines_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.machines_table.setObjectName("machines_table")
        self.machines_table.setColumnCount(0)
        self.machines_table.setRowCount(0)
        self.machine_label = QtWidgets.QLabel(self.machine)
        self.machine_label.setGeometry(QtCore.QRect(60, 20, 301, 41))
        self.machine_label.setObjectName("machine_label")
        self.back_btn_2 = QtWidgets.QPushButton(self.machine)
        self.back_btn_2.setGeometry(QtCore.QRect(40, 370, 101, 41))
        self.back_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_2.setObjectName("back_btn_2")
        self.next_btn_3 = QtWidgets.QPushButton(self.machine)
        self.next_btn_3.setGeometry(QtCore.QRect(290, 370, 101, 41))
        self.next_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn_3.setObjectName("next_btn_3")
        self.stackedWidget.addWidget(self.machine)
        self.review = QtWidgets.QWidget()
        self.review.setObjectName("review")
        self.bookings_table = QtWidgets.QTableWidget(self.review)
        self.bookings_table.setGeometry(QtCore.QRect(50, 80, 351, 271))
        self.bookings_table.setStyleSheet("QTableWidget {\n"
"    gridline-color: #dcdde1;\n"
"    selection-background-color: #aed6f1;\n"
"    selection-color: #1a5276;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"")
        self.bookings_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bookings_table.setObjectName("bookings_table")
        self.bookings_table.setColumnCount(0)
        self.bookings_table.setRowCount(0)
        self.booking_label = QtWidgets.QLabel(self.review)
        self.booking_label.setGeometry(QtCore.QRect(60, 20, 311, 41))
        self.booking_label.setObjectName("booking_label")
        self.back_btn_3 = QtWidgets.QPushButton(self.review)
        self.back_btn_3.setGeometry(QtCore.QRect(50, 370, 91, 41))
        self.back_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn_3.setObjectName("back_btn_3")
        self.confrim_btn = QtWidgets.QPushButton(self.review)
        self.confrim_btn.setGeometry(QtCore.QRect(240, 370, 161, 41))
        self.confrim_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confrim_btn.setObjectName("confrim_btn")
        self.stackedWidget.addWidget(self.review)
        self.machine_icon = QtWidgets.QLabel(Dialog)
        self.machine_icon.setGeometry(QtCore.QRect(470, 10, 51, 51))
        self.machine_icon.setText("")
        self.machine_icon.setPixmap(QtGui.QPixmap(":/machine/icons8-washing-machine-94.png"))
        self.machine_icon.setScaledContents(True)
        self.machine_icon.setObjectName("machine_icon")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.date_label.setText(_translate("Dialog", "Select a date for your laundry booking"))
        self.next_btn.setText(_translate("Dialog", "Next"))
        self.timeslot_label.setText(_translate("Dialog", "Select a time slot"))
        self.back_btn.setText(_translate("Dialog", "Back"))
        self.next_btn_2.setText(_translate("Dialog", "Next"))
        self.machine_label.setText(_translate("Dialog", "Choose a washing machine"))
        self.back_btn_2.setText(_translate("Dialog", "Back"))
        self.next_btn_3.setText(_translate("Dialog", "Next"))
        self.booking_label.setText(_translate("Dialog", "Review and confirm your booking."))
        self.back_btn_3.setText(_translate("Dialog", "Back"))
        self.confrim_btn.setText(_translate("Dialog", "Confirm booking"))
import machine_rc
