# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 586)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.machine_icon = QtWidgets.QLabel(self.centralwidget)
        self.machine_icon.setGeometry(QtCore.QRect(530, 0, 51, 51))
        self.machine_icon.setText("")
        self.machine_icon.setPixmap(QtGui.QPixmap(":/machine/icons8-washing-machine-94.png"))
        self.machine_icon.setScaledContents(True)
        self.machine_icon.setObjectName("machine_icon")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(90, 120, 411, 91))
        self.name_label.setStyleSheet(" color: #ffffff;\n"
"font-weight: bold;\n"
" margin-bottom: 5px;\n"
"font-size: 40px;\n"
"qproperty-alignment: AlignCenter;")
        self.name_label.setObjectName("name_label")
        self.tagline_label = QtWidgets.QLabel(self.centralwidget)
        self.tagline_label.setGeometry(QtCore.QRect(40, 210, 521, 51))
        self.tagline_label.setStyleSheet("    color: #ffffff;\n"
"    font-weight: normal;\n"
"    margin-bottom: 5px;\n"
"     font-size: 20px;\n"
"    qproperty-alignment: AlignCenter;")
        self.tagline_label.setObjectName("tagline_label")
        self.log_out = QtWidgets.QPushButton(self.centralwidget)
        self.log_out.setGeometry(QtCore.QRect(470, 490, 91, 41))
        self.log_out.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_out.setStyleSheet("color: #ffffff;\n"
"border-radius: 6px;\n"
"font-size: 14px;\n"
"text-decoration: underline\n"
"\n"
"")
        self.log_out.setObjectName("log_out")
        self.bubbles_label = QtWidgets.QLabel(self.centralwidget)
        self.bubbles_label.setGeometry(QtCore.QRect(0, 0, 581, 561))
        self.bubbles_label.setText("")
        self.bubbles_label.setPixmap(QtGui.QPixmap("bubbles.gif"))
        self.bubbles_label.setScaledContents(True)
        self.bubbles_label.setObjectName("bubbles_label")
        self.bubbles_label.raise_()
        self.machine_icon.raise_()
        self.name_label.raise_()
        self.tagline_label.raise_()
        self.log_out.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuUsers = QtWidgets.QMenu(self.menuBar)
        self.menuUsers.setObjectName("menuUsers")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAdmin = QtWidgets.QAction(MainWindow)
        self.actionAdmin.setObjectName("actionAdmin")
        self.action_students = QtWidgets.QAction(MainWindow)
        self.action_students.setObjectName("action_students")
        self.action_admin = QtWidgets.QAction(MainWindow)
        self.action_admin.setObjectName("action_admin")
        self.menuUsers.addAction(self.action_students)
        self.menuUsers.addAction(self.action_admin)
        self.menuBar.addAction(self.menuUsers.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Yiqa"))
        self.tagline_label.setText(_translate("MainWindow", "Welcome to Yiqa — Fast. Easy. Reliable"))
        self.log_out.setText(_translate("MainWindow", "Log out"))
        self.menuUsers.setTitle(_translate("MainWindow", "Users"))
        self.actionAdmin.setText(_translate("MainWindow", "Admin"))
        self.action_students.setText(_translate("MainWindow", "Students"))
        self.action_admin.setText(_translate("MainWindow", "Admin"))
import machine_rc
